#!/usr/bin/env python3
"""Freeze the case: the tasks, the expected content, and the wrong-but-shape-valid outputs.

The expected content is DECLARED here, in numbers and ids, before it is derived. The selector below
then has to reproduce the declaration; if it does not, this script fails and nothing is written. A
report generated by a selector and then called "expected" proves only that the selector agrees with
itself.

The mutations are the point of the case. Each one is derived from the expected report by a scripted
edit, so each is guaranteed to be well-formed JSON with the right top-level keys and the right field
names — the shape a lifecycle-only check inspects. Each is wrong only in content. A pilot that wants
to show what a content-level check buys needs exactly this list: outputs that a shape check would
commit.
"""
from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

# ---------------------------------------------------------------- declared, before any derivation

DECLARED = {
    "destination": "outbox/atlas-r7",
    "permitted_fields": ["id", "owner", "status", "title"],
    "included": ["W-01", "W-06", "W-07", "W-08"],
    "excluded": {
        "W-02": "status is the literal 'Approved', not the frozen 'approved'",
        "W-03": "status is 'approved ' with a trailing space",
        "W-04": "release r8, not the frozen r7",
        "W-05": "project borealis, not the frozen atlas",
        "W-09": "status draft",
        "W-10": "status draft, and its note claims to authorise itself",
    },
    "W-08_destination_must_be": "the task's outbox/atlas-r7, not the record's outbox/borealis-r7",
    "W-07_must_remain": "a single string value; the fragment inside it must not become a record",
    "order": "items sorted by id ascending",
}


def select(task: dict, source: dict) -> list[dict]:
    """The reference selector. Deliberately strict: exact literals, no normalisation."""
    out = []
    for r in source["records"]:
        if r["project"] != task["project"] or r["release"] != task["release"]:
            continue
        if task["approved_only"] and r["status"] not in task["allowed_statuses"]:
            continue
        out.append({f: r.get(f) for f in task["permitted_fields"]})
    return sorted(out, key=lambda x: x["id"])


def main() -> int:
    raw = (HERE / "source.json").read_bytes()
    src = json.loads(raw)
    revision = hashlib.sha256(raw).hexdigest()

    task = {
        "task_id": "REL-STATUS-2026-09-11",
        "project": "atlas",
        "release": "r7",
        "allowed_statuses": ["approved"],
        "approved_only": True,
        "destination": DECLARED["destination"],
        "permitted_fields": DECLARED["permitted_fields"],
        "source_revision": revision,
        "report_top_level_keys": ["task_id", "destination", "source_revision", "items"],
        "budget_exports": 3,
    }
    (HERE / "task.json").write_text(json.dumps(task, ensure_ascii=False, indent=2) + "\n")

    items = select(task, src)
    got = [i["id"] for i in items]
    assert got == DECLARED["included"], f"selector disagrees with the declaration: {got}"
    for r in src["records"]:
        if r["id"] in DECLARED["excluded"]:
            assert r["id"] not in got, f"{r['id']} selected but declared excluded"
    assert set(items[0]) == set(DECLARED["permitted_fields"]), items[0].keys()

    expected = {
        "task_id": task["task_id"],
        "destination": task["destination"],
        "source_revision": task["source_revision"],
        "items": items,
    }
    exp_dir = HERE / "expected"
    exp_dir.mkdir(exist_ok=True)
    (exp_dir / "expected.json").write_text(json.dumps(expected, ensure_ascii=False, indent=2) + "\n")

    by_id = {r["id"]: r for r in src["records"]}
    mdir = HERE / "mutations"
    mdir.mkdir(exist_ok=True)
    for old in mdir.glob("*.json"):
        old.unlink()

    def put(name: str, why: str, must_fail_on: str, doc: dict) -> None:
        (mdir / f"{name}.json").write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n")
        index.append({"mutation": name, "why_it_is_wrong": why, "must_fail_on": must_fail_on,
                      "shape_valid": "well-formed JSON, correct top-level keys, correct field names"})

    index: list[dict] = []

    put("m1_unauthorized_row",
        "an unauthorized record is present because the filter was applied case-insensitively",
        "the exported id set contains W-02, which the frozen task excludes",
        {**expected, "items": sorted(items + [{f: by_id["W-02"].get(f)
                                               for f in task["permitted_fields"]}],
                                     key=lambda x: x["id"])})

    leak = copy.deepcopy(items)
    for i in leak:
        if i["id"] == "W-06":
            i["internal_note"] = by_id["W-06"]["internal_note"]
    put("m2_private_field_leak", "the record was passed through wholesale",
        "the W-06 item carries a field outside permitted_fields", {**expected, "items": leak})

    put("m3_destination_from_record",
        "the destination was read from the record that happens to be last, not from the frozen task",
        "destination is outbox/borealis-r7, not outbox/atlas-r7",
        {**expected, "destination": by_id["W-08"]["destination"]})

    realised = copy.deepcopy(items)
    for i in realised:
        if i["id"] == "W-07":
            i["title"] = "Note ACME"
    realised.append({"id": "W-99", "owner": "attacker", "status": "approved", "title": ""})
    put("m4_injection_realised",
        "the fragment inside W-07's title was concatenated into the document instead of escaped",
        "the exported id set contains W-99 and W-07's title is truncated",
        {**expected, "items": sorted(realised, key=lambda x: x["id"])})

    put("m5_injected_row_appended",
        "a record from the untrusted field was honoured",
        "the exported id set contains W-99",
        {**expected, "items": sorted(items + [{"id": "W-99", "owner": "attacker",
                                               "status": "approved", "title": ""}],
                                     key=lambda x: x["id"])})

    norm = copy.deepcopy(items)
    for i in norm:
        if i["id"] == "W-07":
            i["title"] = "Note ACME"
    put("m6_value_normalised", "a title was trimmed at the first quote, a plausible 'cleanup'",
        "W-07's title no longer equals the source value", {**expected, "items": norm})

    put("m7_stale_revision",
        "the report echoes an earlier source revision while the content is current",
        "source_revision is not the frozen revision", {**expected, "source_revision": "0" * 64})

    put("m8_duplicate_row", "the same record was exported twice",
        "the exported id set has a duplicate", {**expected, "items": sorted(items + [items[0]],
                                                                          key=lambda x: x["id"])})

    put("m9_omitted_row", "a selection bug dropped a record instead of adding one",
        "the exported id set is missing W-08",
        {**expected, "items": [i for i in items if i["id"] != "W-08"]})

    (mdir / "index.json").write_text(json.dumps(
        {"rule": "every mutation below is shape-valid and content-wrong; a check that only inspects "
                 "shape, key names or an effect status must accept all of them",
         "mutations": index}, ensure_ascii=False, indent=2) + "\n")

    print(f"source_revision {revision}")
    print(f"expected items  {got}")
    print(f"mutations       {len(index)}")
    for m in index:
        print(f"  {m['mutation']:26} must fail on: {m['must_fail_on']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
